version: 1.0

.common_params: &common_params
  resolve_s3: true
  region: 'eu-central-1'
  confirm_changeset: 'true'
  capabilities: 'CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM'
  image_repositories: []

test:
  deploy:
    parameters:
      <<: *common_params
      s3_prefix: 'test-flutter-google-login'
      stack_name: 'test-flutter-google-login'
      parameter_overrides:
        - Env="test"
        - ProjectName="flutter-google-login"
        - UserPoolDomainName="flutter-google-login"
        - UserPoolName="flutter-google-login"
        - GoogleClientId="264295797329-ef2td1nkqcken25noq6v9fbr48ddeg4p.apps.googleusercontent.com" # TODO put in secret manager / parameter store
        - GoogleClientSecret="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" # TODO put in secret manager
      tags:
        - 'Environment=test'
        - 'ProjectName=flutter-google-login'
